# Generated by Django 5.2 on 2025-08-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0138_configurable_mt_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="userchat",
            name="total_words_generated",
            field=models.IntegerField(
                default=0, help_text="Number of words generated in this chat."
            ),
        ),
    ]
